### PR TITLE
improved autopatrol and fixed launchfiles for turtlebot and simulation

### PR DESCRIPTION
**Pull request by audiocarnage**

### CODE REVIEW

**Comment by DeeVeX** [comment]
Not working when trying to catkin_make the package.

> CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by "rplidar_ros" with
>   any of the following names:
>     rplidar_rosConfig.cmake
>     rplidar_ros-config.cmake

**Comment by audiocarnage** [comment]
I'm sorry, forgot to mention this, you have to get two other packages for simulation and turtlebot.

git clone https://github.com/tu-darmstadt-ros-pkg/hector_models
git clone https://github.com/robopeak/rplidar_ros

**Comment by DeeVeX** [comment]
Something is still fishy. When executing `roslaunch robopatrol simulation.launch` the following error occurs:

> while processing /home/turtlebot/rosproject/catkin_robopatrol/src/robopatrol/launch/includes/simulation.launch.xml:
> Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/turtlebot/rosproject/catkin_robopatrol/src/robopatrol/launch/includes/simulation.launch.xml'

**Comment by audiocarnage** [comment]
Do you have this file on your computer? Should be in ~/catkin_ws/src/robopatrol/launch/includes/simulation.launch.xml

**Comment by DeeVeX** [comment]
No. How can i generate this file?
I placed your two repositories in my `~/catkin_ws/src/` directory and built those by executing `catkin_make` again.

**Comment by audiocarnage** [comment]
It's a new file, I added it in this PR. I have optimised the launch files for simulation and turtlebot.

**Comment by DeeVeX** [comment]
Sounds nice. Could you commit this file to your branch? It is missing.

**Comment by audiocarnage** [comment]
This is weird... I thought I did commit the updated launchfiles with the XML includes.... just gimme a second.

**Comment by audiocarnage** [comment]
should be fine now

**Comment by DeeVeX** [comment]
Nice, thank you. Autopatrol seems indeed to be improved. Let us hope the real robot will act equally.

**Comment by audiocarnage** [comment]
Thank you

**Pull request merged**
