### PR TITLE
Rp 39 save multiple maps from exploring

### PR DESCRIPTION
**Pull request by sidloki**
- initialize the db with some maps (playground, willow, icclab)
- service to start/stop the map_server
- service to start slam_gmapping and save the map
- service to delete a map

### CODE REVIEW

**Comment by audiocarnage** [comment]
The node map_service dies when I launch robopatrol.launch:

HTTPConnectionPool(host='0.0.0.0', port=9998): Max retries exceeded with url: /maps (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

Robopatrol Server (docker container) is up and listens on port 9998...

**Comment by sidloki** [comment]
No idea about this error. I've used gradle to bring up the robopatrol-server.

**Comment by sidloki** [comment]
Should work now. The problem was, that the map service creates some default maps on node startup, but the rest server is not yet running.

**Comment by audiocarnage** [comment]
something is still broken.

from robopatrol import srv
ImportError: cannot import name srv

**Comment by chilloutman** [comment]
Ideally the ros nodes should be able to handle the REST server being down and retry the requests, until the REST server is up.

A bit too late for that now, though...

**Comment by chilloutman** [comment]
Gogogo. Let's merge whatever works now. Improve later.

**Pull request merged**
