### PR TITLE
images folder

### PR DESCRIPTION
**Pull request by joshfreak7**
Created images folder and moved pics from root to this folder. I assume links to pix in wiki-pages have to be adjusted.

### CODE REVIEW

**Comment by chilloutman** [comment]
We should probably move those ui drawings to [robopatrol-webapp](https://github.com/robopatrol/robopatrol-webapp) since that's where the ui is.

Also, is it intentional that this pull request includes a test map?

**Comment by joshfreak7** [comment]
Initially, this branch was for the testmap, so that's why it is in here.
For the images, you're right, I just wanted to clean up the "root" folder.

**Comment by chilloutman** [comment]
Can you move the files?

**Comment by joshfreak7** [comment]
UI-drawings moved to webapp repository.

**Comment by chilloutman** [comment]
I'll close this one. Reopen when these images are removed.

**Comment by chilloutman** [comment]
I've removed the images in this commit: 81fee471aac894f494f02270cb108d4832ad94b9.

Closing PR now.

**Pull request closed without merging**
