### PR TITLE
added necessary rplidar_ros and hector_models packages

### PR DESCRIPTION
**Pull request by audiocarnage**
- for simulation and turtlebot patrol

### CODE REVIEW

**Comment by audiocarnage** [comment]
Packages **rplidar_ros** and **hector_models** are not built by catkin_make.
How can we solve this problem?

**Comment by chilloutman** [comment]
So, on your machine you have cloned the two repositories into the catkin workspace too?

**Comment by audiocarnage** [comment]
yes, works just fine on my machine. 6 packages are built in total:
- hector_components_description
- hector_models (metapackage)
- hector_sensors_description
- hector_xacro_tools
- rplidar_ros
- robopatrol

**Comment by chilloutman** [comment]
ok, the parts with `~/catkin_ws` should use `$robopatrol_ws` instead. That way we are sure that the workspace path is always correct.

**Comment by chilloutman** [comment]
This would break the build for everyone that isn't using Docker, unless they know to clone the two repositories. This should be added to the `README.md`.

**Comment by audiocarnage** [comment]
Thank you! I already updated the project setup part in our wiki.

**Comment by chilloutman** [comment]
Working now? Feel free to merge.

**Comment by audiocarnage** [comment]
It works, thanks!

**Pull request merged**
