### PR TITLE
#RP-22 Robot finds his charging station

### PR DESCRIPTION
**Pull request by audiocarnage**
untested code, need map with virtual "charging station" to test this module

### CODE REVIEW

**Comment by chilloutman** [comment]
Some unit tests, maybe?

**Comment by chilloutman** [comment]
@simmljoe you still working on this?

**Comment by simmljoe** [comment]
@chilloutman nope, freezed atm. @SimonGadgeteer and @audiocarnage are working on this, but maybe it is not nessecary..

**Comment by chilloutman** [comment]
Any news on this? I'll close this PR for now. Please re-open if we still want to merge this.

**Pull request closed without merging**
