### PR TITLE
#RP-48  added better quality map of turtlebot_world

### PR DESCRIPTION
**Pull request by audiocarnage**

### CODE REVIEW

**Comment by audiocarnage** [comment]
ERROR: Failure: ImportError (No module named robopatrol.helloworld)

Srsly, do we really need a hello world! unit test ?

**Comment by steffinchen** [comment]
No, we don't need a helloWorld test, but currently it's the only test we have in this project, so lets keep it as a placeholder (and to make sure test execution works). 
Marco fixed the issue with the ImportError in the Travis build, so make sure you have current version of .travis.yml from master branch in your branch.

**Comment by chilloutman** [comment]
Status? @audiocarnage, should this be reviewed and merged, or are you still working?

**Comment by chilloutman** [comment]
I'm a bit worried about all the different `.launch` files.

We need a single launch file that launches all of the functionality.

Something like:
- `robopatrol.launch`: Launches all of the robopatrol functionality.
- `turtlebot_robopatrol.launch`: Launches `robopatrol.launch` and the turtlebot packages for testing. (I assume that on the bot the turtlebot packages are already running.)

**Pull request merged**
